services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8181:8080"
    networks:
      - backend
    command:
      - start-dev

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rmq3"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  db:
    image: mysql:9.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: springmicroserviceuser
      MYSQL_PASSWORD: 111111
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./init:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    networks:
      - backend

  # phpMyAdmin
  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=db
    - PMA_USER=springmicroserviceuser
    - PMA_PASSWORD=111111
    ports:
    - 5051:80
    networks:
      - backend

networks:
  backend:
    driver: bridge
